extended header with logo and made it somewhat responsive
ReDI-School/job-board pull request #19
Opened 2021-04-12 15:25 UTC by kantimam

2021-04-12 15:28 UTC, kantimam commented
looks like typescript is somewhat of a bully with static files images etc. and the linter does not allow ignoring the line

2021-04-12 16:55 UTC, lopis commented on package.json
> +
😱  what happened here?

2021-04-13 01:31 UTC, kantimam commented
looks like resolving conflicts in yarn.lock is kinda messy I will just do it in my IDE tomorrow

2021-04-14 15:09 UTC, lopis requested changes

2021-04-14 15:09 UTC, lopis commented on src/pages/AddJobPage.tsx
> +      <Container>to be implemented</Container>
I only meant this to be a link to the form, but actually this page might be useful.

2021-04-14 15:09 UTC, lopis commented on src/customTypes.d.ts
> +declare module '*.gif';
```suggestion
declare module '*.gif';

```
Missing new line

2021-04-14 15:10 UTC, lopis approved these changes

2021-04-14 15:13 UTC, merged