Add translation support
ReDI-School/job-board pull request #26
Opened 2021-04-16 07:48 UTC by maroun-baydoun

I chose not to use a third-party library for the time being. Instead, I re-used some code I had created for a different project to give basic support for multiple language. The API is similar to `react-intl`. In the future, we could easily replace the code with a third-party solution if there's need for that. 

I added only support for English with a single string to test the flow. We will add more languages and strings as we decide on what languages to support and the content to show on the web app. 

Closes #12

2021-04-16 10:15 UTC, lopis requested changes
I like this solution. It's quite concise. I just added a couple suggestions to missing/unnecessary line breaks.

2021-04-16 10:15 UTC, lopis commented on src/i18n/useIntl.ts
> +  return useMemo(
Good one. TIL.

2021-04-16 10:15 UTC, lopis commented on src/i18n/index.ts
> +
```suggestion
```

2021-04-16 10:15 UTC, lopis commented on src/i18n/index.ts
> +
```suggestion
```

2021-04-16 10:15 UTC, lopis commented on src/i18n/index.ts
> +
```suggestion
```

2021-04-16 10:15 UTC, lopis commented on src/i18n/index.ts
> +
```suggestion
```

2021-04-16 10:15 UTC, lopis commented on translations/en.json
> +}
```suggestion
}

```

2021-04-16 10:15 UTC, lopis commented on src/i18n/index.ts
> +import enTranslationMessages from '../../translations/en.json';
The main issue here is that we'll be importing all languages always. But we can worry about that in the future. I like this solution!

2021-04-18 13:57 UTC, maroun-baydoun commented on src/i18n/index.ts
> +import enTranslationMessages from '../../translations/en.json';
You're right. I didn't want to complicate the solution at this stage. We will definitely tackle that once we add more languages.

2021-04-19 07:33 UTC, lopis approved these changes
👍🏼

2021-04-19 21:32 UTC, merged