Moj footer
ReDI-School/job-board pull request #27
Opened 2021-04-16 23:25 UTC by mojvaf

I need your thoughts about the footer? Do we  need to add links to facebook and tweeter with their icons?

2021-04-17 05:25 UTC, lopis commented
Sure, you can add those social icons. A couple remarks though :

 - Please add a proper title to your pull request.
 - The footer must be inside <footer>

On Sat, Apr 17, 2021, 01:26 mojvaf ***@***.***> wrote:

> I need your thoughts about the footer? Do we need to add links to facebook
> and tweeter with their icons?
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/lopis/job-board/pull/27
> Commit Summary
>
>    - created the footer
>    - created the footer
>
> File Changes
>
>    - *M* src/components/Footer.tsx
>    <https://github.com/lopis/job-board/pull/27/files#diff-0dce242c6c493ad784b03374bef9541bc63a42693fdb79e88c6dda5e76fbac04>
>    (42)
>    - *M* yarn.lock
>    <https://github.com/lopis/job-board/pull/27/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2de>
>    (1295)
>
> Patch Links:
>
>    - https://github.com/lopis/job-board/pull/27.patch
>    - https://github.com/lopis/job-board/pull/27.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lopis/job-board/pull/27>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAUXAZ4YP55HCD53XZVTT7TTJDBQZANCNFSM43CMZBIA>
> .
>

2021-04-20 20:13 UTC, maroun-baydoun requested changes

2021-04-20 20:13 UTC, maroun-baydoun commented on src/components/Footer.tsx
> +      backgroundColor:'#757575',
Instead of hard-coding the colors, it'd better to take them from the `theme` object if possible.

2021-04-20 20:13 UTC, maroun-baydoun commented on src/components/Footer.tsx
> +    <div className={classes.root}>
Instead of `div`, a `footer` element would be more appropriate here.

2021-04-21 13:04 UTC, mojvaf commented
Please take look at the footer

2021-04-21 16:02 UTC, maroun-baydoun requested changes

2021-04-21 16:02 UTC, maroun-baydoun commented on src/components/Footer.tsx
> +      backgroundColor: "green",
Let's try to use as many colours from the theme as possible, instead of hardcoded ones.

2021-04-21 17:32 UTC, lopis commented
@mojvaf Please also remember to run the command `yarn lint`. This will show several problems in your code, and fix a few of them.  To keep all the code uniform, we have defined strict code style rules, including things like tab size, using only single-quoted strings, and always using semi-colons.

2021-04-22 16:41 UTC, lopis commented
@mojvaf please write here what error you're getting.

2021-04-22 18:17 UTC, mojvaf commented
> @mojvaf please write here what error you're getting.

 ! [remote rejected] moj-footer -> moj-footer (permission denied)
error: failed to push some refs to 'https://github.com/lopis/job-board.git'

2021-04-22 19:40 UTC, lopis commented
Oh, i'm sorry. That's because we have moved the repository from my account to ReDI's account! You need to update the link of your git remote. Try this:

`git remote set-url origin git@github.com:ReDI-School/job-board.git`

2021-04-22 19:42 UTC, lopis commented
You'll also need to merge with the `main` branch and run `yarn` to re-install dependencies and fix the conflicts.

2021-04-22 21:14 UTC, mojvaf commented
> You'll also need to merge with the `main` branch and run `yarn` to re-install dependencies and fix the conflicts.



> You'll also need to merge with the `main` branch and run `yarn` to re-install dependencies and fix the conflicts.

Could you please explain more because I never merge anything to main. I wait until someone checks my code. I always create my branch and when I finish and ask for Pull Request.  Also when you said run yarn did you mean yarn dev? This is my first big project that I am doing with more than one person so sorry for some basic questions.

2021-04-23 06:17 UTC, lopis commented
> Could you please explain more because I never merge anything to main. I wait until someone checks my code.

No, I meant the other way around. Your branch has become outdated from the `main` branch, so you need to bring it up-to-date by merging the new changes _from master_.

```
git fetch
git merge origin/master
```

This will cause some conflicts. To solve conflicts in the `yarn.lock` file you run `yarn` (the command used to install the dependencies). This will fix those conflicts. Please read more about git and dealing with conflicts. This is normal to happen when a PR stays open for a while and there are many people working on the same project.

2021-05-04 20:06 UTC, lopis commented
Closing this PR, as it was superseded by #33

2021-05-04 20:07 UTC, closed without merging