Moj footer2
ReDI-School/job-board pull request #33
Opened 2021-04-23 22:28 UTC by mojvaf

could you please check my code and see if needs some changes or not.

2021-04-26 06:55 UTC, lopis commented
I'm confused, why did you create a new pull request?

2021-04-26 07:02 UTC, lopis requested changes
Hello! Please see my comments below.
Also, your `yarn.lock` file is still causing conflicts with the `main` branch; you can't merge if you don't solve them (just run `yarn` to install all dependencies and update the lock file). Finally, if you're done with #27 please close it.

2021-04-26 07:02 UTC, lopis commented on src/components/Footer.tsx
> +        fill:'theme.palette.primary.dark',
`'theme.palette.primary.dark'` is a string. This won't produce the value you want.

2021-04-26 07:02 UTC, lopis commented on src/components/Footer.tsx
> +              <Grid item  /*component={Link} to="/Redi"*/ >Copyright</Grid>
Break long lines.

```suggestion
              <Grid item  /*component={Link} to="/"*/ >
                Home
              </Grid>
              <Grid item  /*component={Link} to="/About"*/ >
                Redi School
              </Grid>
              <Grid item  /*component={Link} to="/Redi"*/ >
                Copyright
              </Grid>
```

2021-04-26 07:02 UTC, lopis commented on src/components/Footer.tsx
> +              <Tweeter className={classes.icon}/>
Did you mean "Twitter"?

2021-04-26 07:02 UTC, lopis commented on src/components/Footer.tsx
> +            <Grid item /*component={"a"} herf="http://www.facebook.com" rel="noopener noreferrer" target="_blank"*/>
Why are the links to social media commented? I think we can already add links to the icons.

2021-04-26 07:14 UTC, lopis commented
Also, I have edited the title and the description of your pull request. It's important for us reviewers that your title and your description clearly describe the code you are submitting.

2021-04-26 20:22 UTC, mojvaf commented
> Hello! Please see my comments below.
> Also, your `yarn.lock` file is still causing conflicts with the `main` branch; you can't merge if you don't solve them (just run `yarn` to install all dependencies and update the lock file). Finally, if you're done with #27 please close it.

Hello!  Today I was very busy but I will work on it tomorrow morning. Also, there is a bug that I am unbale to fix it. The problem is when hover on icons the color won't change. Could someone check it? Thank you

2021-04-27 17:36 UTC, mojvaf commented on src/components/Footer.tsx
> +        fill:'theme.palette.primary.dark',
what should I do then? I changed 'theme.palette.primary.dark' to something like 'green' and everything works with no bug but I need to use theme color. Any suggestions?

2021-04-27 17:39 UTC, mojvaf commented on src/components/Footer.tsx
> +              <Tweeter className={classes.icon}/>
Yes I meant Twitter. I corrected it. Thanks

2021-04-27 17:40 UTC, mojvaf commented on src/components/Footer.tsx
> +            <Grid item /*component={"a"} herf="http://www.facebook.com" rel="noopener noreferrer" target="_blank"*/>
I corrected it too

2021-04-28 06:17 UTC, lopis commented on src/components/Footer.tsx
> +        fill:'theme.palette.primary.dark',
It's not supposed to be a string, but a value, like so: `fill: theme.palette.primary.dark,`

2021-04-28 17:49 UTC, lopis commented
If you fix the issues I described in the comments related to the theme, that issue with the icons will also be fixed.

2021-04-28 22:43 UTC, mojvaf commented on src/components/Footer.tsx
> +        fill:'theme.palette.primary.dark',
Thank you

2021-05-04 19:06 UTC, lopis commented on src/components/Footer.tsx
> +              <Tweeter className={classes.icon}/>
I still see Tweeter

2021-05-04 19:44 UTC, lopis commented
Thanks for the patiente @mojvaf! I think it looks fine now. I pushed some extra changes because I made a mistake in the code-style auto-fixer, but now it looks ok.

2021-05-04 19:44 UTC, lopis approved these changes

2021-05-05 07:01 UTC, merged

2021-05-05 07:13 UTC, lopis commented
@all-contributors let's add @mojvaf for code!

2021-05-05 09:04 UTC, lopis commented
@all-contributors let's add @mojvaf for code!

2021-05-05 09:20 UTC, mojvaf commented
> @all-contributors let's add @mojvaf for code!

Thanks