Moj hero
ReDI-School/job-board pull request #48
Opened 2021-05-08 15:10 UTC by mojvaf

Please check the hero part. I have not worked on responsive design yet.

2021-05-08 18:01 UTC, lopis commented
Hello. Please change the PR title to a more descriptive title. It also helps us reviewers if you explain in the PR description what you did in this PR. 

Oh, and there are conflicts with the main branch (meaning that your branch is out of date).

2021-05-08 18:11 UTC, lopis requested changes

2021-05-08 18:11 UTC, lopis commented on src/components/Footer.tsx
>        }
I would honestly suggest removing this hover effect. I think it looks a little odd. Also, this PR is about the hero, not the footer.

2021-05-08 18:11 UTC, lopis commented on src/components/Hero.tsx
> +      <Grid item style={{ marginTop: '2rem', marginLeft: '15rem'}}>
Could you move these inline styles out, and use `useStyles` like we did in other components?

2021-05-08 18:11 UTC, lopis commented on src/components/Hero.tsx
> +          }}/>
There's something wrong with the indentation here. Do you use VSCode? If you setup the extensions Editor Config and ESLint it should auto-fix this kind of issues.

2021-05-08 18:11 UTC, lopis commented on src/components/Hero.tsx
> +
Unnecessary empty line

2021-05-08 18:11 UTC, lopis commented on src/components/Hero.tsx
> +
Unnecessary empty line

2021-05-08 18:11 UTC, lopis commented on src/components/Hero.tsx
> +      <Grid item >
```suggestion
      <Grid item>
```

2021-05-08 18:11 UTC, lopis commented on src/components/Hero.tsx
> +const Hero=()=> {
```suggestion
const Hero = () => {
```

2021-05-09 10:56 UTC, mojvaf commented on src/components/Footer.tsx
>        }
I deleted it.

2021-05-09 11:06 UTC, mojvaf commented on src/components/Hero.tsx
> +          }}/>
I use VSCode and I've already installed both extensions. I uninstalled them and then reinstalled them but I don't know what is wrong. Do you have any idea how to make them work? Thanks

2021-05-09 11:12 UTC, mojvaf commented on src/components/Hero.tsx
> +      <Grid item >
sorry I missed to correct this one.

2021-05-09 11:13 UTC, mojvaf commented
Corrected some styling issues

2021-05-18 06:18 UTC, lopis commented on src/components/Hero.tsx
> +
```suggestion
```

2021-05-18 06:18 UTC, lopis commented on src/layouts/PageLayout.tsx
> +
```suggestion
```

2021-05-18 06:19 UTC, lopis commented on src/components/Hero.tsx
> +
```suggestion
```

2021-05-18 06:20 UTC, lopis approved these changes
I pushed a couple cosmetic commits, removing unnecessary empty lines from the code, and I fixed your conflicts with the main branch. Good job, and sorry for the late review!

2021-05-18 06:22 UTC, lopis commented
@mojvaf the code style check is failing in several places. Please check the code styling issues and try again. Don't forget to do `git pull` before, becase I pushed some changes.

https://github.com/ReDI-School/job-board/pull/48/checks?check_run_id=2607597720

2021-05-18 06:33 UTC, lopis commented on src/components/Hero.tsx
> +          }}/>
I'm not sure what might be missing in your setup, but you can always run `yarn lint` yourself and it will tell you the code style problems that your code has before you push them.

2021-05-22 05:25 UTC, merged